### ISSUE TITLE
Problem with the pop-up window before the survey for the whistleblower

### ISSUE THREAD

**Issue by dawnog** [globaleaks/whistleblowing-software#4200]
### What version of GlobaLeaks are you using?

5.0.10

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

I made a new survey. so there were two: mine and the original one.
When I pressed the button to send the submissions, a dialog box appears, with buttons continue and close.
If I press continue it takes me to fill out the whistleblower survey

After removing my survey and plugging the original survey into the channel - the dialog box keeps popping up

Then I received the following message by email

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1089, in _commit_impl
    self.engine.dialect.do_commit(self.connection)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()

sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 187, in _wrap
    session.commit()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 836, in commit
    trans.commit()

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2459, in commit
    self._do_commit()

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2649, in _do_commit
    self._connection_commit_impl()

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2620, in _connection_commit_impl
    self.connection._commit_impl()

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1091, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1089, in _commit_impl
    self.engine.dialect.do_commit(self.connection)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
(Background on this error at: https://sqlalche.me/e/14/gkpj)

**Comment by evilaliv3** [comment]
Thank you @dawnog 

Are you referring to the disclaimer?

That is defined as global level in the content settings and is not related to the questionnaires.
If you have enabled it by mistake in the content settings you could disable it 

P.s. the exception that you are reporting is probably related to something else.

**Comment by karlludwigweise** [comment]
@dawnog you can disable the disclaimer in the basic settings. See https://docs.opensource-hinweisgeberportal.de/globaleaks/admin/settings/basic-settings

**Comment by dawnog** [comment]
Thank you!, there was indeed a space there. It helped. Closing

**Comment by dawnog** [comment]
thank you for your help
