### ISSUE TITLE
error at Password setting

### ISSUE THREAD

**Issue by Thomas-wta** [globaleaks/whistleblowing-software#4202]
### What version of GlobaLeaks are you using?

Version 5.011 (new setup on Debian 6.1.106-3)

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

when a user changes his password, i get up to 4 email with this trackback:
OverflowError Result too large to be represented.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/__init__.py", line 36, in get_receivertips
    updated_before = datetime.fromtimestamp(int(args.get(b'updated_before', [b'32503680000'])[0]))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

OverflowError: timestamp out of range for platform time_t

what's the problem? missed i something during installation?
By that i can't ad a reciepent.

Regards Thomas

**Comment by evilaliv3** [comment]
Hello @Thomas-wta 

Thank you for reporting this.

Actually globaleaks for some reasons requires a 64 bits; is it possible that you are running on a 32 bit system?

**Comment by evilaliv3** [comment]
I've improved the documentation adding details about 64-bit requirement.
