### ISSUE TITLE
Creating Account Recovery Key fails during first user session

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/whistleblowing-software#4211]
### What version of GlobaLeaks are you using?

5.0.11

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When a new user is added to a portal, we always recommend, that they immediately create the Account Recovery Key. On the later versions we have noticed, that this isn't possible.

After setting the password the user enters his/her account and select Account Recovery key. The password box is shown, but when entering in the password and clicking the "Confirm" an error message comes up.

After logging out and in again, the procedure issucessful.

I've identified the following in globaleaks.log:

2024-10-02 09:16:25+0000 [-] [E] Unhandled exception raised:
2024-10-02 09:16:25+0000 [-] [E] nacl.exceptions.TypeError None\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/user/operation.py", line 115, in get_recovery_key\n    return Base32Encoder.encode(GCE.asymmetric_decrypt(user_cc, Base64Encoder.decode(user.crypto_rec_key.encode()))).replace(b'=', b'')\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 301, in asymmetric_decrypt\n    prv_key = PrivateKey(prv_key, Base64Encoder)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 90, in __init__\n    "bytes long raw secret key").format(self.SIZE)\n\nnacl.exceptions.TypeError: PrivateKey must be created from a 32 bytes long raw secret key\n

An error mail had following content:

Platform: TEST - Whistleblower
Host: <redacted>
Version: 5.0.11

nacl.exceptions.TypeError None

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/user/operation.py", line 115, in get_recovery_key
    return Base32Encoder.encode(GCE.asymmetric_decrypt(user_cc, Base64Encoder.decode(user.crypto_rec_key.encode()))).replace(b'=', b'')

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 301, in asymmetric_decrypt
    prv_key = PrivateKey(prv_key, Base64Encoder)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 90, in __init__
    "bytes long raw secret key").format(self.SIZE)

nacl.exceptions.TypeError: PrivateKey must be created from a 32 bytes long raw secret key

**Comment by evilaliv3** [comment]
Thank you @schris-dk ;

Let us check on this and we will get back to you.

**Comment by evilaliv3** [comment]
Hello @schris-dk , actually this was a rare bug to find since it happens only on system where the system is used without escrow keys (https://docs.globaleaks.org/en/main/security/EncryptionProtocol.html#key-escrow)

In this condition users at their first login could not access the escrow key.
I'm going to fix this with a patch that will be included in 5.0.12.

**Comment by evilaliv3** [comment]
Thank you @agenceKanvas . Will recheck and ensure to issue a release that corrects your situation that i think is related but slitghtly different.
